config/routes.rb
TtBettingApp::Application.routes.draw do

  devise_for :users

  get "welcome/index"

  mount TtBetting::Engine, :at => "/betting"

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_protected
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def require_admin
    unless current_user.is_superuser
      flash[:error] = 'Only admin has access to this page.'
      redirect_to :root
    end
  end

  def require_normal_user
    if current_user.is_superuser
      flash[:error] = 'Only normal users have access to this page.'
      redirect_to :root
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def global_path path_helper, engine = nil
    if engine
      engine::Engine.routes.url_helpers.send(path_helper)
    else
      Rails.application.routes.url_helpers.send(path_helper)
    end
  end

end

app/helpers/authorization_helper.rb
module AuthorizationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>TtBettingApp</title>
    <%= stylesheet_link_tag "bootstrap", :media => "all" %>
    <%= yield :stylesheets %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "bootstrap.min" %>
    <%= javascript_include_tag "application" %>
    <%= yield :javascripts %>
    <%= csrf_meta_tags %>
</head>
<body>

<header>
    <div class="header_wrapper">
        <div class="pull-left logo_wrapper">
            <a href=""><%= image_tag "logo.gif" %></a>
        </div>

        <% if current_user %>
            <%= yield :tt_betting_top_tabs %>
        <% end %>
        <div class="logout navbar-text pull-right">
            <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', main_app.edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", main_app.destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
                <%= link_to "Sign up", main_app.new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", main_app.new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
        </div>


    </div>
</header>

<div class="content">
    <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
    <% end %>

    <%= content_for?(:content) ? yield(:content) : yield %>
</div>



</body>
</html>

app/views/welcome/index.html.erb
<%= link_to "TT Betting Engne", tt_betting_path %>